## Data Cleaning of Amazon Product Data

In [2]:
import pandas as pd

In [19]:
df = pd.read_csv('amazon_data.csv')

In [20]:
df.head()

,product_id,discounted_price,actual_price,discount_percentage,rating,rating_count
0,B07JW9H4J1,399.0,1099.0,64%,4.2,"24,269"
1,B098NS6PVG,199.0,349.0,43%,4,"43,994"
2,B096MSW6CT,199.0,1899.0,90%,3.9,"7,928"
3,B08HDJ86NZ,329.0,699.0,53%,4.2,"94,363"
4,B08CF3B7N1,154.0,399.0,61%,4.2,"16,905"

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   discounted_price     1465 non-null   str
 2   actual_price         1465 non-null   str
 3   discount_percentage  1465 non-null   str
 4   rating               1465 non-null   str
 5   rating_count         1463 non-null   str
dtypes: str(6)
memory usage: 68.8 KB

In [8]:
df.shape

(1463, 6)

In [7]:
df.dropna(inplace=True)

In [13]:
df['actual_price'] = (
    df['actual_price']
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [15]:
df['discounted_price'] = (
    df['discounted_price']
    .str.replace('₹', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

In [16]:
df.head()

,product_id,discounted_price,actual_price,discount_percentage,rating,rating_count
0,B07JW9H4J1,399.0,1099.0,64%,4.2,"24,269"
1,B098NS6PVG,199.0,349.0,43%,4,"43,994"
2,B096MSW6CT,199.0,1899.0,90%,3.9,"7,928"
3,B08HDJ86NZ,329.0,699.0,53%,4.2,"94,363"
4,B08CF3B7N1,154.0,399.0,61%,4.2,"16,905"

In [18]:
df = df.to_csv('amazon_data.csv', index=False)